// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A flow to generate SEO-optimized titles and descriptions for pottery pieces.
 *
 * - seoOptimizePottery - A function that generates SEO-optimized content for pottery.
 * - SEOOptimizePotteryInput - The input type for the seoOptimizePottery function.
 * - SEOOptimizePotteryOutput - The return type for the seoOptimizePottery function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SEOOptimizePotteryInputSchema = z.object({
  name: z.string().describe('The current name of the pottery piece.'),
  description: z.string().describe('The current description of the pottery piece.'),
  style: z.string().describe('The style of the pottery piece (e.g., modern, rustic, minimalist).'),
  technique: z.string().describe('The technique used to create the pottery piece (e.g., wheel-thrown, hand-built, sculpted).'),
  keywords: z.string().describe('Existing SEO keywords. Separate multiple keywords with commas.'),
});
export type SEOOptimizePotteryInput = z.infer<typeof SEOOptimizePotteryInputSchema>;

const SEOOptimizePotteryOutputSchema = z.object({
  title: z.string().describe('An SEO-optimized title for the pottery piece.'),
  description: z.string().describe('An SEO-optimized description for the pottery piece.'),
});
export type SEOOptimizePotteryOutput = z.infer<typeof SEOOptimizePotteryOutputSchema>;

export async function seoOptimizePottery(input: SEOOptimizePotteryInput): Promise<SEOOptimizePotteryOutput> {
  return seoOptimizePotteryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'seoOptimizePotteryPrompt',
  input: {schema: SEOOptimizePotteryInputSchema},
  output: {schema: SEOOptimizePotteryOutputSchema},
  prompt: `You are an SEO expert specializing in optimizing product listings for handcrafted pottery.

  Given the following information about a pottery piece, generate an alternative SEO-optimized title and description that will attract more customers and improve search engine rankings. The response must be appropriate for use on an e-commerce website.

  Current Name: {{{name}}}
Current Description: {{{description}}}
Style: {{{style}}}
Technique: {{{technique}}}
Existing Keywords: {{{keywords}}}

  Focus on incorporating relevant keywords naturally and creating compelling, informative content.
  The title should be concise and attention-grabbing. The description should be detailed, highlighting the unique aspects of the pottery and its appeal to potential buyers.
  Ensure that your response conforms to valid JSON format.
  `,
});

const seoOptimizePotteryFlow = ai.defineFlow(
  {
    name: 'seoOptimizePotteryFlow',
    inputSchema: SEOOptimizePotteryInputSchema,
    outputSchema: SEOOptimizePotteryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
